export const commandIds = [
  'handleArrowDown',
  'handleArrowUp',
  'handleBlur',
  'handleClick',
  'handleEnd',
  'handleFilterInput',
  'handleFocus',
  'handleHome',
  'handleResizerMouseDown',
  'handleResizerMouseMove',
  'handleResizerMouseUp',
  'handleSelectedContentClick',
  'selectIndex',
  'terminate',
]
