export const HandleFilterInput = 'handleFilterInput'
export const HandleClick = 'handleClick'
export const HandleResizerMouseDown = 'handleResizerMouseDown'
export const HandleResizerMouseMove = 'handleResizerMouseMove'
export const HandleResizerMouseUp = 'handleResizerMouseUp'
export const HandleSelectedContentClick = 'handleSelectedContentClick'
export const HandleFocus = 'handleFocus'
export const HandleBlur = 'handleBlur'
