export const Data = 'Data'
export const Length = 'Length'
export const NoMessageSelected = 'No message selected'
export const NoMessagesFound = 'No messages found'
export const FilterMessages = 'Filter messages...'
